<? 
include_once(APPPATH.'/models/Entity.php');

class TindakLanjut extends Entity { 

	var $query;

    function TindakLanjut()
	{
      	$this->Entity(); 
    }
 
 
	function selectByParamsRekomendasi($paramsArray=array(),$limit=-1,$from=-1, $statement='', $sOrder="ORDER BY OUTLINING_ASSESSMENT_REKOMENDASI_ID ASC")
	{
		$str = "
			SELECT A.*,B.WO || ' - ' || B.DESCRIPTION NAMA_WO,F.NAMA,F.KODE || GENERATEZERO(G.KODE,2) || ' - ' || F.NAMA KODE_INFO,H.NAMA ITEM_ASSESSMENT_INFO
		, I.NAMA JENIS_NAMA
		, J.NAMA PRIORITAS_NAMA
		, K.NAMA  KATEGORI_NAMA
		, C.BULAN,C.TAHUN
		, L.NAMA STATUS_INFO
		, DR.DISTRIK_ID
		, DR.NAMA DISTRIK_INFO
		, BU.NAMA BLOK_INFO
		FROM OUTLINING_ASSESSMENT_REKOMENDASI A
		LEFT JOIN WORK_ORDER B ON B.WORK_ORDER_ID = A.WORK_ORDER_ID
		INNER JOIN OUTLINING_ASSESSMENT C ON C.OUTLINING_ASSESSMENT_ID = A.OUTLINING_ASSESSMENT_ID
		INNER JOIN OUTLINING_ASSESSMENT_DETIL D ON D.OUTLINING_ASSESSMENT_DETIL_ID = A.OUTLINING_ASSESSMENT_DETIL_ID
		INNER JOIN OUTLINING_ASSESSMENT_AREA_DETIL E ON E.OUTLINING_ASSESSMENT_AREA_DETIL_ID = A.OUTLINING_ASSESSMENT_AREA_DETIL_ID
		INNER JOIN LIST_AREA F ON F.LIST_AREA_ID = D.LIST_AREA_ID
		INNER JOIN ITEM_ASSESSMENT_DUPLIKAT G ON G.ITEM_ASSESSMENT_DUPLIKAT_ID = D.ITEM_ASSESSMENT_DUPLIKAT_ID AND G.LIST_AREA_ID = D.LIST_AREA_ID
		INNER JOIN ITEM_ASSESSMENT_FORMULIR H ON H.ITEM_ASSESSMENT_FORMULIR_ID = E.ITEM_ASSESSMENT_FORMULIR_ID
		LEFT JOIN JENIS_REKOMENDASI I ON I.JENIS_REKOMENDASI_ID = A.JENIS_REKOMENDASI_ID
		LEFT JOIN PRIORITAS_REKOMENDASI J ON J.PRIORITAS_REKOMENDASI_ID = A.PRIORITAS_REKOMENDASI_ID
		LEFT JOIN KATEGORI_REKOMENDASI K ON K.KATEGORI_REKOMENDASI_ID = A.KATEGORI_REKOMENDASI_ID
		LEFT JOIN STATUS_REKOMENDASI L ON L.STATUS_REKOMENDASI_ID = A.STATUS_REKOMENDASI_ID
		LEFT JOIN DISTRIK DR ON DR.DISTRIK_ID = C.DISTRIK_ID
		LEFT JOIN BLOK_UNIT BU ON BU.BLOK_UNIT_ID = D.BLOK_UNIT_ID
		LEFT JOIN UNIT_MESIN UM ON UM.UNIT_MESIN_ID = C.UNIT_MESIN_ID

		WHERE 1=1
		"; 
		
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$sOrder;
		$this->query = $str;
				
		return $this->selectLimit($str,$limit,$from); 
	}


	function selectByParamsRekomendasiNull($paramsArray=array(),$limit=-1,$from=-1, $statement='', $sOrder="ORDER BY C.DISTRIK_ID ASC")
	{
		$str = "
		SELECT A.*,F.NAMA,F.KODE || GENERATEZERO(G.KODE,2) || ' - ' || F.NAMA KODE_INFO,H.NAMA ITEM_ASSESSMENT_INFO
		, C.BULAN,C.TAHUN
		, DR.DISTRIK_ID
		, DR.NAMA DISTRIK_INFO
		, BU.NAMA BLOK_INFO
		, E.DETAIL
		, I.NAMA JENIS_NAMA
		, J.NAMA PRIORITAS_NAMA
		, K.NAMA  KATEGORI_NAMA
		, E.OUTLINING_ASSESSMENT_REKOMENDASI_ID
		FROM OUTLINING_ASSESSMENT_AREA_DETIL A
		INNER JOIN OUTLINING_ASSESSMENT C ON C.OUTLINING_ASSESSMENT_ID = A.OUTLINING_ASSESSMENT_ID
		INNER JOIN OUTLINING_ASSESSMENT_DETIL D ON D.OUTLINING_ASSESSMENT_DETIL_ID = A.OUTLINING_ASSESSMENT_DETIL_ID
		LEFT JOIN OUTLINING_ASSESSMENT_REKOMENDASI E ON E.OUTLINING_ASSESSMENT_AREA_DETIL_ID = A.OUTLINING_ASSESSMENT_AREA_DETIL_ID
		INNER JOIN LIST_AREA F ON F.LIST_AREA_ID = D.LIST_AREA_ID
		INNER JOIN ITEM_ASSESSMENT_DUPLIKAT G ON G.ITEM_ASSESSMENT_DUPLIKAT_ID = D.ITEM_ASSESSMENT_DUPLIKAT_ID AND G.LIST_AREA_ID = D.LIST_AREA_ID
		INNER JOIN ITEM_ASSESSMENT_FORMULIR H ON H.ITEM_ASSESSMENT_FORMULIR_ID = A.ITEM_ASSESSMENT_FORMULIR_ID
		LEFT JOIN JENIS_REKOMENDASI I ON I.JENIS_REKOMENDASI_ID = E.JENIS_REKOMENDASI_ID
		LEFT JOIN PRIORITAS_REKOMENDASI J ON J.PRIORITAS_REKOMENDASI_ID = E.PRIORITAS_REKOMENDASI_ID
		LEFT JOIN KATEGORI_REKOMENDASI K ON K.KATEGORI_REKOMENDASI_ID = E.KATEGORI_REKOMENDASI_ID
		LEFT JOIN STATUS_REKOMENDASI L ON L.STATUS_REKOMENDASI_ID = E.STATUS_REKOMENDASI_ID
		LEFT JOIN DISTRIK DR ON DR.DISTRIK_ID = C.DISTRIK_ID
		LEFT JOIN BLOK_UNIT BU ON BU.BLOK_UNIT_ID = C.BLOK_UNIT_ID
		LEFT JOIN UNIT_MESIN UM ON UM.UNIT_MESIN_ID = C.UNIT_MESIN_ID

		WHERE 1=1

		"; 
		
		while(list($key,$val) = each($paramsArray))
		{
			$str .= " AND $key = '$val' ";
		}
		
		$str .= $statement." ".$sOrder;
		$this->query = $str;
				
		return $this->selectLimit($str,$limit,$from); 
	}


  
} 
?>